<div class="page-title">
    <h1><?php echo $this->getPost()->getTitle(); ?></h1>
</div>
<div class="post-metadata">
    <ul>
        <li class="post-time">
            <?php echo $this->__('Created On: '); ?>
            <?php $date = $this->getPost()->getCreatedAt();?>
            <?php echo Mage::app()->getLocale()->date($date)->toString();?>
        </li>
    </ul>
</div>
<div class="post-content">
    <?php echo $this->getPost()->getContentHtml(); ?>
</div>