<?php
/**
 * Created by PhpStorm.
 * User: ThaoHoang
 * Date: 7/26/2016
 * Time: 15:48
 */

$installer = $this;
$installer->startSetup();

$neotheme_blog_category = array(
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 10:37:01','updated_at' => '2016-07-27 10:37:03','status' => '1','name' => 'Foods & Beverages','summary' => 'Foods & Beverages','store_ids' => '2','cms_identifier' => 'Foods & Beverages','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:12:01','updated_at' => '2016-07-27 15:12:03','status' => '1','name' => 'Foods & Beverages','summary' => 'Foods & Beverages','store_ids' => '3','cms_identifier' => 'Foods & Beverages','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:13:06','updated_at' => '2016-07-27 15:13:07','status' => '1','name' => 'Foods & Beverages','summary' => 'Foods & Beverages','store_ids' => '4','cms_identifier' => 'Foods & Beverages','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:13:54','updated_at' => '2016-07-27 15:13:56','status' => '1','name' => 'Foods & Beverages','summary' => 'Foods & Beverages','store_ids' => '5','cms_identifier' => 'Foods & Beverages','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:15:00','updated_at' => '2016-07-27 15:15:01','status' => '1','name' => 'Foods & Beverages','summary' => 'Foods & Beverages','store_ids' => '6','cms_identifier' => 'Foods & Beverages','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:15:39','updated_at' => '2016-07-27 15:15:40','status' => '1','name' => 'Foods & Beverages','summary' => 'Foods & Beverages','store_ids' => '7','cms_identifier' => 'Foods & Beverages','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:16:20','updated_at' => '2016-07-27 15:16:21','status' => '1','name' => 'Materials','summary' => 'Materials','store_ids' => '2','cms_identifier' => 'Materials','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:17:00','updated_at' => '2016-07-27 15:17:02','status' => '1','name' => 'Materials','summary' => 'Materials','store_ids' => '3','cms_identifier' => 'Materials','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:17:30','updated_at' => '2016-07-27 15:17:31','status' => '1','name' => 'Materials','summary' => 'Materials','store_ids' => '4','cms_identifier' => 'Materials','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:18:42','updated_at' => '2016-07-27 15:18:43','status' => '1','name' => 'Materials','summary' => 'Materials','store_ids' => '5','cms_identifier' => 'Materials','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:19:10','updated_at' => '2016-07-27 15:19:12','status' => '1','name' => 'Materials','summary' => 'Materials','store_ids' => '6','cms_identifier' => 'Materials','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:19:34','updated_at' => '2016-07-27 15:19:35','status' => '1','name' => 'Materials','summary' => 'Materials','store_ids' => '7','cms_identifier' => 'Materials','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:20:07','updated_at' => '2016-07-27 15:20:08','status' => '1','name' => 'Recipe e-Books','summary' => 'Recipe e-Books','store_ids' => '2','cms_identifier' => 'Recipe e-Books','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:20:39','updated_at' => '2016-07-27 15:20:40','status' => '1','name' => 'Recipe e-Books','summary' => 'Recipe e-Books','store_ids' => '3','cms_identifier' => 'Recipe e-Books','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:21:04','updated_at' => '2016-07-27 15:21:05','status' => '1','name' => 'Recipe e-Books','summary' => 'Recipe e-Books','store_ids' => '4','cms_identifier' => 'Recipe e-Books','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:21:46','updated_at' => '2016-07-27 15:21:44','status' => '1','name' => 'Recipe e-Books','summary' => 'Recipe e-Books','store_ids' => '5','cms_identifier' => 'Recipe e-Books','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:22:02','updated_at' => '2016-07-27 15:22:01','status' => '1','name' => 'Recipe e-Books','summary' => 'Recipe e-Books','store_ids' => '6','cms_identifier' => 'Recipe e-Books','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:22:20','updated_at' => '2016-07-27 15:22:19','status' => '1','name' => 'Recipe e-Books','summary' => 'Recipe e-Books','store_ids' => '7','cms_identifier' => 'Recipe e-Books','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:23:10','updated_at' => '2016-07-27 15:23:09','status' => '1','name' => 'Cooking Appliances','summary' => 'Cooking Appliances','store_ids' => '2','cms_identifier' => 'Cooking Appliances','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:23:44','updated_at' => '2016-07-27 15:23:43','status' => '1','name' => 'Cooking Appliances','summary' => 'Cooking Appliances','store_ids' => '3','cms_identifier' => 'Cooking Appliances','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:24:09','updated_at' => '2016-07-27 15:24:08','status' => '1','name' => 'Cooking Appliances','summary' => 'Cooking Appliances','store_ids' => '4','cms_identifier' => 'Cooking Appliances','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:24:24','updated_at' => '2016-07-27 15:24:22','status' => '1','name' => 'Cooking Appliances','summary' => 'Cooking Appliances','store_ids' => '5','cms_identifier' => 'Cooking Appliances','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:24:45','updated_at' => '2016-07-27 15:24:44','status' => '1','name' => 'Cooking Appliances','summary' => 'Cooking Appliances','store_ids' => '6','cms_identifier' => 'Cooking Appliances','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:25:11','updated_at' => '2016-07-27 15:25:09','status' => '1','name' => 'Cooking Appliances','summary' => 'Cooking Appliances','store_ids' => '7','cms_identifier' => 'Cooking Appliances','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:26:50','updated_at' => '2016-07-27 15:26:49','status' => '1','name' => 'Customized Meals','summary' => 'Customized Meals','store_ids' => '2','cms_identifier' => 'Customized Meals','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:27:10','updated_at' => '2016-07-27 15:27:08','status' => '1','name' => 'Customized Meals','summary' => 'Customized Meals','store_ids' => '3','cms_identifier' => 'Customized Meals','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:27:42','updated_at' => '2016-07-27 15:27:41','status' => '1','name' => 'Customized Meals','summary' => 'Customized Meals','store_ids' => '4','cms_identifier' => 'Customized Meals','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:27:47','updated_at' => '2016-07-27 15:27:48','status' => '1','name' => 'Customized Meals','summary' => 'Customized Meals','store_ids' => '5','cms_identifier' => 'Customized Meals','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:28:07','updated_at' => '2016-07-27 15:28:09','status' => '1','name' => 'Customized Meals','summary' => 'Customized Meals','store_ids' => '6','cms_identifier' => 'Customized Meals','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL),
    array('entity_id' => null,'parent_id' => '0','created_at' => '2016-07-27 15:28:31','updated_at' => '2016-07-27 15:28:32','status' => '1','name' => 'Customized Meals','summary' => 'Customized Meals','store_ids' => '7','cms_identifier' => 'Customized Meals','root_template' => 'one_column','layout_update_xml' => NULL,'meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL)
);

foreach ($neotheme_blog_category as $category){
    Mage::getModel('neotheme_blog/category')->setData($category)->save();
}

$installer->endSetup();