<div style="margin: 10px; display: none" id="baybanbua_terms_conditions">
	<div style="border: 1px solid #e5e5e5; height: 200px; overflow: auto; padding: 10px; margin: 5px; font-style: italic;">
		I confirm that I give BayBanBua company permission to deliver my items bought at Très Bien. If any of my items are lost, broken or malfunctioned during shipping period, I will take full responsibility and will not sue either BayBanBua or Très Bien or Mr. Khue Nguyen Quang.
	</div>
	<div class="checkbox">
        <label>
            <input type="checkbox" name="agree" id="cb_baybanbua_term" /> I agree
        </label>
    </div>
</div>
