<!DOCTYPE html>
<html>
<head>
    <title>Payment Gateway Page</title>
    <?php echo $this->getChildHtml('head') ?>
<body>
<center>
    <h2>KIMOCHI GATE</h2>
    <?php 
        $orderDetail = Mage::app()->getRequest()->getParam('orderDetail');
        $verifyUrl = $this->getUrl('kimochigate/index/verify',array('orderDetail'=>$orderDetail));
        $cancelUrl = $this->getUrl('kimochigate/index/success',array('orderDetail'=>$orderDetail,'success'=>0));
        $orderDetail = explode('^_^', base64_decode($orderDetail));
    ?>
    <form class="form-horizontal" action="<?php echo $verifyUrl ?>" method="post" id="gate">
        <div class="form-group">
            <label class="control-label col-sm-3" for="name">Name<span class="required"></span></label>
            <div class="col-sm-9">
                <input style="margin-bottom: 10px" id="name" name="name" class="required-entry form-control" type="text" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="cardno">Card Number<span class="required"></span></label>
            <div class="col-sm-9">
                <input id="cardno" name="card-number" class="form-control required-entry" type="text" style="margin-bottom: 10px"/>
            </div>
        </div>
        <div class="form-group"> 
            <input type="button" name="next" id="next_verify" class="btn btn-success" value="Thanh toán" />
            <a href="<?php echo $cancelUrl ?>" class="btn btn-danger">Cancel</a>
        </div>
    </form>
    <div>
        <p>Bạn đang thực hiện thanh toán đơn hàng: #<?php echo $orderDetail[0]?></p>
        <?php
            $price = $orderDetail[1];
            if ('USD' == $orderDetail[2]) {
                $price *=20000;
            }
        ?>
        <p>Số tiền cần thanh toán là: <?php echo $price.' VNĐ'?></p>
    </div>
    <script type="text/javascript" charset="utf-8">
        var urlPaid = <?php echo json_encode($this->getUrl('kimochigate/index/paid', array('price'=>$price)));?>
    </script>
</center> 
</body>
</html>