<style>
	.logo_bank {
		margin-left: 16px;
		margin-top: 5px;
		border: 1px solid white;
		float: left;
	}

	.credit-card {
		width: 550px;
		padding: 10px;
	}

	.selected {
		border: 1px solid firebrick;
	}
	.woocommerce #payment ul.payment_methods li img, .woocommerce-page #payment ul.payment_methods li img {
		vertical-align: middle;
		margin: 7px !important;
		position: relative;
	}
</style>
<ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
	<li>
		<?php echo $this->getMethod()->get_seller_info($this->getMethodCode()); ?>
	</li>
</ul>


