<?php if ($this->getCategoryId()):?>
    <div class="page-title">
        <h1><?php echo $this->getCategory()->getName();?></h1>
    </div>
<?php endif; ?>
<?php if (!$this->getPostCollectionByTag()->count()):?>
    <div class="note-msg"><?php echo Mage::helper('neotheme_blog')->__('There are no posts in this category'); ?></div>
<?php else: ?>
    <?php foreach($this->getPostCollectionByTag() as $post):?>
        <div class="blog blog-summary">
            <?php 
            echo $this->getSummaryBlock($post)->toHtml();
            ?>
        </div>
    <?php endforeach; ?>
    <div class="toolbar"><?php echo $this->getPagerHtml(); ?></div>
<?php endif;?>
